- name: Configure app
  hosts: reddit-app
  become: true

  roles:
    - app

    - role: jdauphant.nginx
      nginx_http_params:
        - sendfile "on"
        - access_log "/var/log/nginx/access.log"
      nginx_sites:
        server:
          - listen 80
          - location / { proxy_pass http://127.0.0.1:9292/; } 
      nginx_configs:
        proxy:
          - proxy_set_header X-Real-IP  $remote_addr
          - proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for
